name: KrylovQuantumClassical
channels: 
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - numba
  - matplotlib
  - joblib
  - spherical
  - quaternionic
  - wolframclient
  - ipykernel